///////////////////////////////////////////////////////////////////
// Filename: corsair_example_tb_pkg.sv
// Author  : Benjamin Tamayo
// Date    : 2026-10-08
// Purpose : Testbench package for the Corsair integration example.
///////////////////////////////////////////////////////////////////

package corsair_example_tb_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  // The UVC.
  import axi_lite_pkg::*;

  // The register model, generated from regs.json by
  // tools/corsair_uvc_gen.py. Regenerated by `make regs`.
  import corsair_example_reg_pkg::*;

  // Note what is NOT imported: corsair_example_regs_pkg, Corsair's own
  // SystemVerilogPackage export. It does not compile.
  //
  // Corsair v1.0.4 writes a field's enumerated values as an untyped
  // `enum` -- whose base type is therefore `int`, 32 bits -- with sized
  // literals inside it:
  //
  //     typedef enum { CSR_CTRL_MODE_IDLE = 2'h0, ... } csrctrl_mode_t;
  //
  // IEEE 1800-2017 section 6.19 requires a sized literal in an enum to
  // match the base type's width, so this is illegal SystemVerilog and
  // XSIM rejects the whole package:
  //
  //     ERROR: [VRFC 10-3291] enum literal 'CSR_CTRL_MODE_IDLE'
  //            width (2) must match enum width (32)
  //
  // corsair_uvc_gen.py therefore emits the same constants itself, as
  // correctly sized localparams, and the generated package above is a
  // drop-in replacement for Corsair's. A map with no enumerated values
  // is unaffected, and so is this example once Corsair fixes it --
  // importing both would then only risk a name collision, which is what
  // the generator's --prefix is for.

  // The port's geometry, from the generated constants rather than
  // restated here, so the testbench and the DUT cannot be parameterized
  // differently.
  parameter int EX_ADDR_WIDTH = CSR_ADDR_WIDTH;
  parameter int EX_DATA_WIDTH = CSR_DATA_WIDTH;

  // The last decoded byte of the map, so stimulus can be kept inside it.
  parameter axi_lite_addr_t EX_MAP_HI = 64'h1B;  // EVENT is at 0x18

  typedef virtual axi_lite_if #(EX_ADDR_WIDTH, EX_DATA_WIDTH) corsair_vif_t;
  typedef axi_lite_agent      #(EX_ADDR_WIDTH, EX_DATA_WIDTH) corsair_agent_t;
  typedef virtual corsair_example_hw_if                       corsair_hw_vif_t;

  `include "corsair_example_macro_model.sv"
  `include "corsair_example_env.sv"
  `include "corsair_example_seq_lib.sv"
  `include "corsair_example_test.sv"

endpackage : corsair_example_tb_pkg
